import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ShieldCheck, ShieldAlert, Play, CheckCircle2, AlertTriangle, Terminal, RefreshCw, Layers } from 'lucide-react';
import { RiskRule } from '../types';

interface RiskFraudTabProps {
  rules: RiskRule[];
  onToggleRule: (ruleId: string) => void;
  securityScore: number;
}

export function RiskFraudTab({ rules, onToggleRule, securityScore }: RiskFraudTabProps) {
  const [isScanning, setIsScanning] = useState(false);
  const [scanLogs, setScanLogs] = useState<string[]>([]);
  const consoleBottomRef = useRef<HTMLDivElement>(null);

  // Simulated scan process
  const triggerScan = () => {
    setIsScanning(true);
    setScanLogs([]);
    const logs = [
      '🚀 Booting PCI-DSS audit framework v2.1...',
      '🔍 Scanning active code pathways in /src/...',
      '📦 Loading composite security checks...',
      '⚠️ ALERT: Found unmasked CARD CVV logging parameters in AuthContext.tsx line 12!',
      '⚠️ WARNING: Settings.tsx is exposing master keys without explicit RBAC wraps.',
      '📝 Parsing database schema index configurations...',
      'ℹ️ INFO: No composite index found on high-throughput columns.',
      '🔐 Auditing JWT configuration flags in server parameters...',
      '✅ Audit scan complete. 3 security flags detected.'
    ];

    let currentLogIndex = 0;
    const interval = setInterval(() => {
      if (currentLogIndex < logs.length) {
        setScanLogs(prev => [...prev, logs[currentLogIndex]]);
        currentLogIndex++;
      } else {
        clearInterval(interval);
        setIsScanning(false);
      }
    }, 700);
  };

  // Keep console scrolled down
  useEffect(() => {
    if (consoleBottomRef.current) {
      consoleBottomRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [scanLogs]);

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Compliant':
        return <ShieldCheck className="w-5 h-5 text-emerald-500" />;
      case 'Warning':
        return <AlertTriangle className="w-5 h-5 text-amber-500" />;
      default:
        return <ShieldAlert className="w-5 h-5 text-red-500 animate-pulse" />;
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'Compliant':
        return <span className="px-2 py-0.5 rounded bg-emerald-50 border border-emerald-100 text-emerald-700 text-[10px] font-bold">Secure</span>;
      case 'Warning':
        return <span className="px-2 py-0.5 rounded bg-amber-50 border border-amber-200 text-amber-700 text-[10px] font-bold">Warning</span>;
      default:
        return <span className="px-2 py-0.5 rounded bg-red-50 border border-red-200 text-red-700 text-[10px] font-bold">Threat Alert</span>;
    }
  };

  return (
    <div className="space-y-6 h-full overflow-y-auto pb-12 pr-1 custom-scrollbar">
      {/* Risk Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Security Gauge */}
        <div className="bg-white p-6 rounded-xl border border-slate-200/80 shadow-sm col-span-1 flex flex-col justify-between">
          <div className="space-y-1">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Security Compliance Health</span>
            <div className="flex items-center gap-4 py-2">
              <div className="relative flex items-center justify-center">
                {/* Simulated circle indicator */}
                <svg className="w-20 h-20 transform -rotate-90">
                  <circle cx="40" cy="40" r="34" className="stroke-slate-100" strokeWidth="6" fill="transparent" />
                  <circle
                    cx="40"
                    cy="40"
                    r="34"
                    className="stroke-blue-600 transition-all duration-700"
                    strokeWidth="6"
                    fill="transparent"
                    strokeDasharray={`${2 * Math.PI * 34}`}
                    strokeDashoffset={`${2 * Math.PI * 34 * (1 - securityScore / 100)}`}
                  />
                </svg>
                <span className="absolute text-sm font-bold text-slate-800">{securityScore}/100</span>
              </div>
              <div className="space-y-1">
                <span className="text-xs font-bold text-slate-700">PCI-DSS Status</span>
                <span className="text-[10px] text-slate-500 font-medium block">Checked against SEC-1 guidelines. 5 critical rules verified.</span>
              </div>
            </div>
          </div>
          <span className="text-[10px] text-slate-400 font-mono">Autogenerated by WalletPro Audit</span>
        </div>

        {/* Threat Level */}
        <div className="bg-white p-6 rounded-xl border border-slate-200/80 shadow-sm col-span-1 flex flex-col justify-between">
          <div className="space-y-1">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Real-Time Threat Level</span>
            <div className="flex items-baseline gap-2 pt-2">
              <span className={`text-3xl font-extrabold font-display ${securityScore > 90 ? 'text-emerald-600' : securityScore > 75 ? 'text-amber-500' : 'text-red-600'}`}>
                {securityScore > 90 ? 'Low' : securityScore > 75 ? 'Elevated' : 'High'}
              </span>
              <span className="text-[10px] text-slate-400 font-medium">score weight</span>
            </div>
            <p className="text-[11px] text-slate-500 font-medium pt-1">
              {securityScore > 90 
                ? 'Your codebase is solid. All high-severity PCI-DSS leak risks resolved.'
                : 'Warning. Unshielded API keys or plain CVV telemetry logs require remediation.'}
            </p>
          </div>
          <span className="text-[10px] text-slate-400 font-mono">Continuous Threat Score</span>
        </div>

        {/* Shield Info */}
        <div className="bg-slate-900 rounded-xl p-6 text-white col-span-1 flex flex-col justify-between">
          <div className="space-y-1">
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Compliance Standard</span>
            <div className="text-lg font-bold font-display mt-2 flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-blue-400" />
              <span>PCI-DSS Validated</span>
            </div>
            <p className="text-slate-400 text-[11px] mt-1 leading-relaxed">
              Platform operates within rigorous cryptographic bounds. Local secrets must reside inside secured ENV profiles.
            </p>
          </div>
          <span className="text-[10px] text-slate-500 font-mono">Valid through 2026</span>
        </div>
      </div>

      {/* Compliance Checklist and Live console */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Rules Checklist (Col 7) */}
        <div className="col-span-12 lg:col-span-7 bg-white rounded-xl border border-slate-200/80 shadow-sm overflow-hidden">
          <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
            <div>
              <h3 className="font-bold text-sm text-slate-800 font-display">Compliance Safeguards</h3>
              <p className="text-[10px] text-slate-400 font-medium">Toggle controls to simulate fixing configuration variables.</p>
            </div>
            <span className="text-[10px] font-bold text-blue-600 bg-blue-100/50 px-2 py-0.5 rounded font-mono uppercase">Interoperable</span>
          </div>

          <div className="p-6 divide-y divide-slate-100">
            {rules.map((rule) => (
              <div key={rule.id} className="py-4 first:pt-0 last:pb-0 flex items-start gap-4">
                <button
                  onClick={() => onToggleRule(rule.id)}
                  className="mt-1 flex items-center justify-center w-5 h-5 rounded border border-slate-300 hover:border-blue-500 bg-slate-50 text-white hover:bg-slate-100 transition-colors select-none cursor-pointer"
                >
                  {rule.status === 'Compliant' && (
                    <div className="w-3.5 h-3.5 rounded bg-blue-600 flex items-center justify-center">
                      <svg className="w-2.5 h-2.5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7" />
                      </svg>
                    </div>
                  )}
                </button>

                <div className="flex-1 space-y-1 text-left">
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-slate-800">{rule.name}</span>
                    {getStatusBadge(rule.status)}
                  </div>
                  <p className="text-[11px] text-slate-500 font-medium leading-relaxed">
                    {rule.description}
                  </p>
                  <div className="text-[10px] text-slate-400 font-mono">
                    Category: {rule.category} | Verified {rule.lastChecked}
                  </div>
                </div>

                <div className="self-center">
                  {getStatusIcon(rule.status)}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Live scanner console (Col 5) */}
        <div className="col-span-12 lg:col-span-5 flex flex-col bg-slate-950 rounded-xl border border-slate-900 shadow-xl overflow-hidden min-h-[350px]">
          {/* Console Header */}
          <div className="px-5 py-3.5 border-b border-slate-900 bg-slate-900/30 flex justify-between items-center">
            <div className="flex items-center gap-2 text-white">
              <Terminal className="w-4 h-4 text-blue-400" />
              <span className="text-xs font-mono font-bold tracking-tight">pci-dss-compliance-scanner.sh</span>
            </div>
            <button
              onClick={triggerScan}
              disabled={isScanning}
              className={`flex items-center gap-1.5 px-3 py-1 bg-slate-800 hover:bg-slate-700 text-white rounded text-[10px] font-bold font-mono transition-colors border border-slate-700/50 cursor-pointer ${
                isScanning ? 'opacity-50 cursor-not-allowed' : ''
              }`}
            >
              {isScanning ? (
                <>
                  <RefreshCw className="w-3 h-3 animate-spin text-blue-400" />
                  <span>Scanning...</span>
                </>
              ) : (
                <>
                  <Play className="w-3 h-3 text-emerald-400" />
                  <span>Run Live Scanner</span>
                </>
              )}
            </button>
          </div>

          {/* Console Logs */}
          <div className="flex-1 p-5 font-mono text-[11px] text-slate-300 space-y-2 overflow-y-auto custom-scrollbar select-text max-h-[350px] text-left">
            {scanLogs.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-slate-500 text-center py-12">
                <ShieldAlert className="w-10 h-10 stroke-1 opacity-20 mb-2 text-slate-400" />
                <span>Console Idle. Click "Run Live Scanner" above to parse files for leaked API keys, credit card numbers, and auth loopholes.</span>
              </div>
            ) : (
              <div className="space-y-2.5">
                {scanLogs.map((log, index) => {
                  let textClass = 'text-slate-300';
                  if (log.startsWith('⚠️ ALERT')) textClass = 'text-red-400 font-bold';
                  else if (log.startsWith('⚠️ WARNING')) textClass = 'text-amber-400 font-bold';
                  else if (log.startsWith('✅')) textClass = 'text-emerald-400 font-bold';
                  else if (log.startsWith('🚀')) textClass = 'text-blue-400 font-semibold';

                  return (
                    <div key={index} className={`${textClass} leading-relaxed`}>
                      {log}
                    </div>
                  );
                })}
                {isScanning && (
                  <div className="flex items-center gap-1 text-slate-500 animate-pulse">
                    <span className="w-1 h-3 bg-slate-400 animate-caret" />
                    <span>Parsing active memory nodes...</span>
                  </div>
                )}
                <div ref={consoleBottomRef} />
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
